version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
    RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
    RABBITMQ_DEFAULT_USER: rabbitmq
    RABBITMQ_DEFAULT_PASS: rabbitmqpasswd
    RABBITMQ_DEFAULT_VHOST: /
volumes:
  rabbitmq: